### ISSUE TITLE
Nodejs dependant version update

### ISSUE THREAD

**Issue by zdmta** [maciejmaciejewski/azure-pipelines-postman#25]
Hi @maciejmaciejewski , 

are there any plans to update plugin to cover this warning: 

##[warning]Task 'Upload Postman HTML Report' version 1 (UploadPostmanHtmlReport@1) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

THanks

**Comment by marcthayer** [comment]
Does anyone have an alternative solution they'd recommend? Pretty sure development here has been abandoned as no commits have been made for 5 years.

**Comment by DK-Dennis** [comment]
I have been extremely grateful for this pipline task, and even if it ends here: Thank you, guys, much appreciated.
I do hope that the original developers of this task will simply update the dependencies and run a new build.
Or maybe someone can fork the code?

In the mean time, until those questions/tasks get sorted ..

I suspect you may buy a little time, if you are using

```
    pool:
      name: Azure Pipelines
      vmImage: 'windows-latest'
```

by changing 'latest' to 'windows-2022'

You can publish the XML testreports, adding them into the 'normal' test views in DevOps pipelines like this:

```
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/Report-TEST.xml' 
        searchFolder: '$(System.DefaultWorkingDirectory)' 
        mergeTestResults: false
        #failTaskOnFailedTests: false # Optional
        testRunTitle: TestRun $(build.buildNumber) TEST (System30)
        #buildPlatform: # Optional
        #buildConfiguration: # Optional
        publishRunAttachments: true
      displayName: "Publish TEST JUnit Test Report"
      condition: succeededOrFailed()
```

But to keep the indeed very nice HTML reports from newman-reporter-htmlextra, you can add them to an artifact drop of the build pipeline, like this:

```
    - task: PublishBuildArtifacts@1
      displayName: 'Publish TEST HTML testreport'
      inputs:
        pathtoPublish: '$(System.DefaultWorkingDirectory)\TESTTestResults' 
        artifactName: 'TestReports'
      condition: succeededOrFailed()
```
