### ISSUE TITLE
Unable to get reports when use multiple agent jobs 

### ISSUE THREAD

**Issue by saikiran40cs** [maciejmaciejewski/azure-pipelines-postman#3]
My scenario is we have 3 collections and each is configured to run as an agent job.
When publishing reports only one collection results are getting published.

![image](https://user-images.githubusercontent.com/6228048/79605381-6bb7ff80-810d-11ea-991d-db3f64db344d.png)

Output: 
![image](https://user-images.githubusercontent.com/6228048/79605426-868a7400-810d-11ea-95f9-5b6c45eb2890.png)

Could you please look into this.

**Comment by maciejmaciejewski** [comment]
@saikiran40cs 
Thanks for reporting the issue. 
I am currently working on this issue in my other extension (Protractor) and will port it here once done.

**Comment by saikiran40cs** [comment]
We are still not able to view two collection results. Could you please let me know if I need to do any change

**Comment by maciejmaciejewski** [comment]
I have been testing using following pipeline configuration

```
  jobs:
  - job: job_1
    displayName: 'Job 1'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UploadPostmanHtmlReport@1
      inputs:
        cwd: '$(System.DefaultWorkingDirectory)/NewmanResults'
        tabName: 'Job 1'
  - job: job_2
    displayName: 'Job 2'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UploadPostmanHtmlReport@1
      inputs:
        cwd: '$(System.DefaultWorkingDirectory)/NewmanResults'
        tabName: 'Job 2'
```

Which gives me following output 
![image](https://user-images.githubusercontent.com/15831316/80373149-e6fb7d00-8894-11ea-8508-47ac1ad42e5b.png)

tabName parameter is optional
